export type { IImage } from './IImage'
export type { IQuestion } from './IQuestion'
export type { PropsWithClassName } from './PropsWithClassname'
export type { ILink } from './ILink'
export type { TId } from './TId'
